const {
  ATTENDANCE_USER_CHECK_IN,
  ATTENDANCE_USER_CHECK_OUT,
  ATTENDANCE_USER_ATTENDANCE
} = require('../../../modules/attendance/endPoints');

module.exports = [
  ATTENDANCE_USER_CHECK_IN,
  ATTENDANCE_USER_CHECK_OUT,
  ATTENDANCE_USER_ATTENDANCE
];
